# Generated by Django 5.2 on 2025-06-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(help_text='e.g., MSc-CS, BSc (Hons) in Computer Science', max_length=200)),
                ('institution', models.CharField(help_text='Name of the educational institution', max_length=200)),
                ('period', models.CharField(help_text='e.g., 2020 - 2023, 2023 - Present', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Additional details about the degree', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this education on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title or position', max_length=200)),
                ('company', models.CharField(help_text='Company or organization name', max_length=200)),
                ('period', models.CharField(help_text='e.g., Jan 2024 - May 2024', max_length=100)),
                ('responsibilities', models.TextField(help_text='Enter each responsibility on a new line')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this experience on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Project name', max_length=200)),
                ('description', models.TextField(help_text='Brief description of the project')),
                ('image', models.ImageField(help_text='Project screenshot or image', upload_to='projects/')),
                ('demo_link', models.URLField(blank=True, help_text='Live demo URL (optional)', null=True)),
                ('code_link', models.URLField(blank=True, help_text='Source code URL (e.g., GitHub)', null=True)),
                ('technologies', models.CharField(blank=True, help_text='Technologies used (comma-separated)', max_length=300)),
                ('category', models.CharField(default='Web App', help_text='Project category', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured projects section')),
                ('is_active', models.BooleanField(default=True, help_text='Show this project on the website')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contact Message', 'verbose_name_plural': 'Contact Messages'},
        ),
    ]
